#!/bin/bash
#function backup () {
	newname=$1.$(date +%d-%m%y).bak
	echo "backup started"
	cp -p $1 $newname


for i [in *.sh]; do
	newname=$i.$(date +%d-%m%y).bak
	echo "backup started"
	cp -p $i $newname
done
